USE SportBase
CREATE TABLE Roles(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(255) NOT NULL,
	AccesRights NVARCHAR(255) NOT NULL,
);

CREATE TABLE Users(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Login NVARCHAR(255) NOT NULL UNIQUE,
	Password NVARCHAR(255) NOT NULL,
	RegistrationDate DATE NOT NULL,
	Surname NVARCHAR(255) NOT NULL,
	Name NVARCHAR(255) NOT NULL,
	Phone NVARCHAR(255) NOT NULL,
	RoleId INT NOT NULL,
	FOREIGN KEY(RoleId) REFERENCES Roles(Id)

);

CREATE TABLE Invetoryes(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	InventoryNumber NVARCHAR(255) NOT NULL UNIQUE,
	Name NVARCHAR(255) NOT NULL,
	Type NVARCHAR(255) NOT NULL,
	Description NVARCHAR(255) NOT NULL,
	PublicationDate DATE NOT NULL,
	State INT CHECK(State in(0,1,2)),
	ReaderId INT NOT NULL,
	FOREIGN KEY(ReaderId) REFERENCES Users(Id)
);