USE CarBase

CREATE TABLE Roles (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
	AccessRights NVARCHAR(MAX) NOT NULL,
);

CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Login NVARCHAR(255) NOT NULL UNIQUE,
    Password NVARCHAR(255) NOT NULL,
    RegistrationDate DATE NOT NULL,
    Surname NVARCHAR(255) NOT NULL,
	Name NVARCHAR(255) NOT NULL,
	Phone NVARCHAR(255) NOT NULL,
    RoleId INT NOT NULL
	FOREIGN KEY (RoleId) REFERENCES Roles(Id)
);

CREATE TABLE Car (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    VIN NVARCHAR(255) NOT NULL,
    Name NVARCHAR(255) NOT NULL,
    Type NVARCHAR(255) NOT NULL,
	Description NVARCHAR(MAX) NOT NULL,
    PublicationDate DATE NOT NULL,
    State INT NOT NULL CHECK (State IN (0,1,2)),
    ReaderId INT NULL,
    FOREIGN KEY (ReaderId) REFERENCES Users(Id)
);